FROM muxelmann/tor

WORKDIR /home

RUN apt update && \
    apt install -y gcc libc6-dev libsodium-dev make autoconf git && \
    git clone https://github.com/cathugger/mkp224o.git


RUN cd mkp224o && ./autogen.sh && ./configure && make && \
    rm -rf /var/lib/apt/lists/*

CMD [ "tor", "-f", "/etc/tor/torrc" ]